# Generated by Django 4.2.5 on 2023-12-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
    ]
